debian/install/deb/etc etc
debian/install/deb/usr/bin/gsettings usr/bin
debian/install/deb/usr/bin/gdbus usr/bin
debian/install/deb/usr/share/man/man1/gio-querymodules.1* usr/share/man/man1
debian/install/deb/usr/share/man/man1/glib-compile-schemas.1* usr/share/man/man1
debian/install/deb/usr/share/man/man1/gsettings.1* usr/share/man/man1
debian/install/deb/usr/share/man/man1/gdbus.1* usr/share/man/man1

